"""empty message

Revision ID: 024780aa36fc
Revises: a35607f1cd9f
Create Date: 2022-11-08 22:48:41.042005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024780aa36fc'
down_revision = 'a35607f1cd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_department', sa.String(length=140), nullable=True),
    sa.Column('class_code', sa.String(length=140), nullable=True),
    sa.Column('professor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_table_class_code'), 'class_table', ['class_code'], unique=False)
    op.create_index(op.f('ix_class_table_class_department'), 'class_table', ['class_department'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_table_class_department'), table_name='class_table')
    op.drop_index(op.f('ix_class_table_class_code'), table_name='class_table')
    op.drop_table('class_table')
    # ### end Alembic commands ###
