"""empty message

Revision ID: 3f425313e663
Revises: 024780aa36fc
Create Date: 2022-11-15 11:03:44.401691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f425313e663'
down_revision = '024780aa36fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_number', sa.Integer(), nullable=True),
    sa.Column('Assigned', sa.Boolean(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['college_course.course_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_numbers_Assigned'), 'permission_numbers', ['Assigned'], unique=False)
    op.create_index(op.f('ix_permission_numbers_professor_id'), 'permission_numbers', ['professor_id'], unique=False)
    op.create_index(op.f('ix_permission_numbers_student_id'), 'permission_numbers', ['student_id'], unique=False)
    op.drop_index('ix_class_table_class_code', table_name='class_table')
    op.drop_index('ix_class_table_class_department', table_name='class_table')
    op.drop_table('class_table')
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.create_table('class_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_department', sa.VARCHAR(length=140), nullable=True),
    sa.Column('class_code', sa.VARCHAR(length=140), nullable=True),
    sa.Column('professor', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['professor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_class_table_class_department', 'class_table', ['class_department'], unique=False)
    op.create_index('ix_class_table_class_code', 'class_table', ['class_code'], unique=False)
    op.drop_index(op.f('ix_permission_numbers_student_id'), table_name='permission_numbers')
    op.drop_index(op.f('ix_permission_numbers_professor_id'), table_name='permission_numbers')
    op.drop_index(op.f('ix_permission_numbers_Assigned'), table_name='permission_numbers')
    op.drop_table('permission_numbers')
    op.drop_table('college_course')
    # ### end Alembic commands ###
