"""empty message

Revision ID: 8696fd4e0d70
Revises: 9c4a790e711e
Create Date: 2022-11-29 13:50:53.023556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8696fd4e0d70'
down_revision = '9c4a790e711e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_requests_owner'), ['owner'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['owner'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requests_owner'))
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
