"""empty message

Revision ID: 5113b3d0301c
Revises: a3dd775f7ab5
Create Date: 2022-11-22 21:32:41.134481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5113b3d0301c'
down_revision = 'a3dd775f7ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission_numbers', schema=None) as batch_op:
        batch_op.drop_index('ix_permission_numbers_Assigned')
        batch_op.drop_index('ix_permission_numbers_course_name')
        batch_op.drop_index('ix_permission_numbers_student_id')

    op.drop_table('permission_numbers')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index('ix_requests_course_id')
        batch_op.drop_index('ix_requests_status')
        batch_op.drop_index('ix_requests_student_id')

    op.drop_table('requests')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_professor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_professor', sa.BOOLEAN(), nullable=True))

    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['college_course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index('ix_requests_student_id', ['student_id'], unique=False)
        batch_op.create_index('ix_requests_status', ['status'], unique=False)
        batch_op.create_index('ix_requests_course_id', ['course_id'], unique=False)

    op.create_table('permission_numbers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('permission_number', sa.INTEGER(), nullable=True),
    sa.Column('Assigned', sa.BOOLEAN(), nullable=True),
    sa.Column('course_name', sa.VARCHAR(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['course_name'], ['college_course.course_name'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission_numbers', schema=None) as batch_op:
        batch_op.create_index('ix_permission_numbers_student_id', ['student_id'], unique=False)
        batch_op.create_index('ix_permission_numbers_course_name', ['course_name'], unique=False)
        batch_op.create_index('ix_permission_numbers_Assigned', ['Assigned'], unique=False)

    # ### end Alembic commands ###
